#!/bin/bash -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

board_info() {
	if [[ "$2" == "rk3576" ]]; then
		case $1 in
			armsom-sige5)
				BOARD_NAME='armsom-sige5'
				BOARD_DTB='rk3576-armsom-sige5.dtb'
				BOARD_uEnv='uEnvarmsom-sige5.txt'
				;;
			armsom-cm5-io)
				BOARD_NAME='armsom-cm5'
				BOARD_DTB='rk3576-armsom-cm5-io.dtb'
				BOARD_uEnv='uEnvarmsom-cm5-io.txt'
				;;
		esac
	elif [[ "$2" == "rk3588" ||  "$2" == "rk3588s" ]]; then
			case $1 in
			armsom-sige7)
				BOARD_NAME='armsom-sige7'
				BOARD_DTB='rk3588-armsom-sige7.dtb'
				BOARD_uEnv='uEnvarmsom-sige7.txt'
				;;
			armsom-aim7-io)
				BOARD_NAME='armsom-aim7-io'
				BOARD_DTB='rk3588-armsom-aim7-io.dtb'
				BOARD_uEnv='uEnvarmsom-aim7-io.txt'
				;;
			*)
				echo "Device ID Error !!!"
				BOARD_NAME='armsom-sige7'
				BOARD_DTB='rk3588-armsom-sige7.dtb'
				BOARD_uEnv='uEnvarmsom-sige7.txt'
				;;
		esac
	fi
				
	echo "BOARD_NAME:"$BOARD_NAME
	echo "BOARD_DTB:"$BOARD_DTB
	echo "BOARD_uEnv:"$BOARD_uEnv
}

board_id() {
	SOC_type=$(cat /proc/device-tree/compatible | tr -d '\0' | cut -d, -f3)
    BOARD_ID=$(cat /proc/device-tree/compatible | tr '\0' '\n' | head -1 | cut -d ',' -f2 | cut -d '-' -f2-)
	echo "SOC_type:"$SOC_type
}

if [ -e /boot/build-host ]; then
	echo "Install kernel package"
else
	board_id
	board_info ${BOARD_ID} ${SOC_type}

	if [ ! -L "/boot/uEnv/uEnv.txt" ] ; then
		echo "ln -sf $BOARD_uEnv /boot/uEnv/uEnv.txt"
		ln -sf $BOARD_uEnv /boot/uEnv/uEnv.txt
	fi
fi

exit 0
